### ISSUE TITLE
The backup date is incorrect and is not updated

### ISSUE THREAD

**Issue by vizzale** [UziTech/sync-settings-folder-location#17] opened 2020-05-01 08:24 UTC
There is a problem related to the backup date: in fact the date that is shown is always the date of the first backup that is made.

**Extended explanation**

1) I make the first backup
2) I close Atom
3) I open Atom: obviously nothing appears because no changes have been made
4) I make a change to the settings
5) I close Atom
6) I open Atom: now the sync-settings plugin correctly warns me that changes have been made

![1](https://user-images.githubusercontent.com/37701762/80691303-59a46c80-8ad0-11ea-8aa6-7baca90a6044.png)

7) click on "View Diff" and the plugin shows me the differences:

![2](https://user-images.githubusercontent.com/37701762/80691349-6a54e280-8ad0-11ea-90b3-84cbb04df3d2.png)

but as you can see from the date this does not change 

8) Though I click on "Backup" the date doesn't change

I have done the procedure several times but the date shown is always wrong, i.e. the date of the first backup is always shown.

**Comment by UziTech** [comment] 2020-05-01 17:14
It gets the last backup time by checking the modified time of the backup folder. We should probably be checking the modified time of each file in the folder.

**Comment by UziTech** [comment] 2020-05-01 18:01
Thanks for taking the time to report this. It should be fixed in v1.0.6.

If the new version does not fix this for you feel free to reopen this issue.

**Comment by vizzale** [comment] 2020-05-01 18:05
> Thanks for taking the time to report this. It should be fixed in v1.0.6.
> 
> If the new version does not fix this for you feel free to reopen this issue.

Thank you for your work 💪🏻❤️

**Comment by vizzale** [comment] 2021-01-30 15:48
Hi @UziTech  you wanted to inform you that unfortunately the same error has been recurring for some time 😔
Is there any way to solve? Thanks so much.

**Comment by UziTech** [comment] 2021-01-30 17:30
Did it work for a while then stop working again? Or has it never worked? Also what OS are you using?

**Comment by vizzale** [comment] 2021-01-30 18:23
It worked and then it stopped working. I'm on macOS Sierra.

**Comment by vizzale** [comment] 2021-02-09 18:01
Hi @UziTech I wanted to update you. 
The problem also occurs if I launch the backup in a Gist.

**Comment by UziTech** [comment] 2021-02-09 20:16
hmm that seems strange. I have not been able to reproduce this to figure out what is going on but I don't have a Mac so it could be something that is only affected by the mac filing system. If you could step through the code and figure out where it is getting the incorrect date that would be very helpful.

**Comment by vizzale** [comment] 2021-02-11 08:59
If I can do something to put you in a position to understand the problem, please tell me.

**Comment by UziTech** [comment] 2021-02-11 16:22
I don't even know where to look because as I said the date updates for me when I test it. You would have to put breakpoints in the script to see where it is getting the wrong date. If you don't know how to do that I think it would be more work than it is worth for me to explain it. 

Does the date really matter to you? or is this just an error that doesn't really cause a problem.

**Comment by vizzale** [comment] 2021-02-12 06:09
> I don't even know where to look because as I said the date updates for me when I test it. You would have to put breakpoints in the script to see where it is getting the wrong date. If you don't know how to do that I think it would be more work than it is worth for me to explain it.

You're right it would be too complicated.

> Does the date really matter to you? or is this just an error that doesn't really cause a problem?

No it's not a huge problem, but having noticed it I wanted to be able to help. Thanks for your patience.

**Comment by UziTech** [comment] 2021-04-22 06:20
If someone is able to reproduce and debug this we can reopen this.

**Closed by UziTech** 2021-04-22 06:20 UTC
Labels: bug, released
